name: release

on:
  pull_request:
    types:
      - closed
    branches:
      - 'main'

jobs:
  run_if:
    if: startsWith(github.head_ref, 'release/') && github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
