name: release

on:
  pull_request:
    branches:
      - main
#    types:
#      - closed

jobs:
  run_if:
#    if: startsWith(github.head_ref, 'release/') && github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:14.5
        env:
          POSTGRES_USER: tester
          POSTGRES_PASSWORD: pgtestpw
          POSTGRES_DB: l0_index
          POSTGRES_PORT: 5432
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 19
        uses: actions/setup-java@v3
        with:
          java-version: '19'
          distribution: 'zulu'

      - name: Build with Maven
        run: mvn package

      - name: Increment version
        uses: RichardInnocent/semantic-versioning-maven@v0.0.34
        with:
          access-token: ${{ secrets.github_token }}

